### ISSUE TITLE
can't read manager/config/settings.js: No such file or directory

### ISSUE THREAD

**Issue by tpargmdiaz** [hardillb/multi-tenant-node-red-k8s#2]
Hi Ben,

I am following your instructions exactly as is in your blog (https://www.hardill.me.uk/wordpress/2020/12/27/multi-tenant-node-red-with-kubernetes/). When running the  setup.sh script I get error below:

```
./setup.sh example.com private.example.com:5000
sed: can't read manager/config/settings.js: No such file or directory
```

**Comment by hardillb** [comment]
You haven't checked out the submodules (as described in the README.md)

**Comment by tpargmdiaz** [comment]
Oh Thank you!

**Comment by tpargmdiaz** [comment]
Ben, I am reading the README, it doesn't say anything about checking out the submodules. It says I have to download the submodule but the script is failing on line 23 cause manager/config/settings.js does not exist.
