### ISSUE TITLE
Manager: INFO  pods is forbidden: User "system:serviceaccount:mt-nodered:create-pod" cannot create resource "pods" in API group "" in the namespace "default"

### ISSUE THREAD

**Issue by tpargmdiaz** [hardillb/multi-tenant-node-red-k8s#4]
Ben,

App Manager is up but I get error 403 when trying to create a nodered pod:

`19:20:36.279 INFO  App listening on  0.0.0.0:3000!
19:20:39.365 INFO  Connected to the DB mongodb://mongo/nodered
181.116.218.63 - admin [28/Sep/2021:19:20:55 +0000] "GET /new.html HTTP/1.1" 200 2847 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
181.116.218.63 - admin [28/Sep/2021:19:20:56 +0000] "GET /picnic.min.css HTTP/1.1" 200 39024 "https://manager.mt-nodered.slot1.io/new.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
181.116.218.63 - admin [28/Sep/2021:19:20:59 +0000] "GET /style.css HTTP/1.1" 200 156 "https://manager.mt-nodered.slot1.io/new.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
19:21:12.369 INFO  pods is forbidden: User "system:serviceaccount:mt-nodered:create-pod" cannot create resource "pods" in API group "" in the namespace "default"
{"code":403,"statusCode":403}
Error: pods is forbidden: User "system:serviceaccount:mt-nodered:create-pod" cannot create resource "pods" in API group "" in the namespace "default"
    at /usr/src/app/node_modules/kubernetes-client/backends/request/client.js:231:25
    at Request._callback (/usr/src/app/node_modules/kubernetes-client/backends/request/client.js:168:14)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
181.116.218.63 - admin [28/Sep/2021:19:21:12 +0000] "POST /instance HTTP/1.1" 500 75 "https://manager.mt-nodered.slot1.io/new.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
![manager403](https://user-images.githubusercontent.com/46410604/135152789-5e9e508b-819f-4f1e-aa41-c78d6bb3ba67.png)

`

**Comment by hardillb** [comment]
There is no role based access control enabled in microk8s so you'll have to work this out yourself.

**Comment by tpargmdiaz** [comment]
Oh I see, I will check how to grant the permissions. Thank you!
